# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled1ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(601, 467)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(9)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 60, 101, 23))
        self.pushButton.setMinimumSize(QtCore.QSize(101, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(101, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 370, 41, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 150, 181, 211))
        self.lineEdit_2.setTabletTracking(False)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(350, 70, 191, 291))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(78, 110, 180, 33))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 601, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.lineEdit)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(self.people)
        self.pushButton_2.clicked.connect(self.lineEdit_2.show)
        self.pushButton_2.clicked.connect(self.lineEdit.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "微信"))
        self.pushButton_2.setText(_translate("MainWindow", "确定"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "请输入你要发送的内容"))
        self.label.setText(_translate("MainWindow", "发送给:"))

    def people(self):
        app = Application().start(r"D:\software\WeChat\WeChat.exe")
        # pyperclip.copy("C:\Program Files (x86)\Tencent\WeChat\WeChat.exe")
        app = Application().connect(path=r"D:\software\WeChat\WeChat.exe")
        send_keys('^f')
        pyperclip.copy(self.lineEdit.text())
        send_keys('^v')
        time.sleep(1)
        pyautogui.press('enter')
        time.sleep(1)
        for i in range(1, 100):
            pyperclip.copy(self.lineEdit_2.text())
            # time.sleep(3)
            send_keys('^v')
            pyautogui.press('enter')


if __name__ == '__main__':
    import sys
    import time
    import pyautogui
    import pyperclip
    import multiprocessing
    from PyQt5 import QtCore, QtGui, QtWidgets
    from PyQt5.QtWidgets import QApplication, QMainWindow
    from PyQt5.QtCore import QThread, pyqtSignal
    from pyautogui import hotkey
    from pywinauto import Application
    from pywinauto.keyboard import send_keys

    # import pics_ui_rc # 导入添加的资源（根据实际情况填写文件名）
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
